functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность переключить язык интерфейса
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя 
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
implicit:
  - При фильтрации товара по цене значение поля ввода «от» не должно быть отрицательным, также значение поля ввода «до» не должно быть меньше значения поля ввода «от»
  - В корзине должна быть возможность изменять количество (как в большую, так и в меньшую сторону) добавляемого товара
  - В корзине при нажатии на кнопку «удалить» должны удаляться все позиции удаляемого товара
  - При удалении товара из корзины должна появляться форма с подтверждением удаления товара
  - При добавлении товара в корзину должна быть возможность указать количество добавляемого товара
  - Должна быть защита от XSS
  - При просмотре информации о товаре должна быть кнопка возвращения на главный экран
  - При оформлении заказа должна появляться форма с подтверждением оформления заказа
